### ISSUE TITLE
5x5cm square .stl file appears to be mm rather than cm

### ISSUE THREAD

**Issue by mikeb127** [radarsimx/radarsimnb#3]
First of all, thank you for creating this library. It's absolutely brilliant to have an open source SBR tool.

I am having some issues with the demo workbook rcs_plate.ipynb. The RCS calculation works perfectly for a 5x5cm plate and matches manual calculations. However when I open the .stl file in FreeCAD software it loads as a 5x5mm square and not a 5x5cm square. I have the same problem with other .stl files I create. (i.e. if I create it in mm, it calculates the RCS as if it were in cm's).

This could also be a bug of FreeCAD, but wanted to check if anyone else is having this issue before I down that route.

**Comment by rookiepeng** [comment]
The stl format doesn't include units. RadarSimPy treats all the values as meters. I think the other software, such as FreeCAD, have their own default units while opening an stl file.

**Comment by mikeb127** [comment]
Ok cool. I will close the issue.

**Comment by ifmfr** [comment]
I do agree @mikeb127 that there is an issue with [Plate RCS](https://radarsimx.com/2021/05/10/plate-rcs/) example. Since STL files do not have a dimension, they are obviously treated as "meter". The example's RCS of the PEC target is 49.36 dBsm, which corresponds to the calculation of 49.41 dBsm (plate 5 x 5 m).
Please double check that. Thanks for your hard work!

**Comment by rookiepeng** [comment]
It is designed to treat STL dimension as "meters" in RadarSimPy

**Comment by ifmfr** [comment]
Sorry, I should have been more precise. My comment is related to the description in "Plate RCS" example, see https://github.com/radarsimx/radarsimnb/pull/4 .
